### ISSUE TITLE
Convert HTML to HAML error

### ISSUE THREAD

**Issue by Dreyfuzz** [handcrafted/handcrafted-haml-textmate-bundle#11]
This is what I get when I try using "Convert HTML to HAML"

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:827:in `report_activate_error': Could not find RubyGem haml (>= 0) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:261:in`activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:68:in `gem'
    from -e:1

This text replaces everything in the current file.  Haml is working.  I'm using haml 3.1.3, Rails 3, Textmate 1.5.10, Ruby 1.9.2-p290, OS 10.6.8.  I installed the bundle into ~/Library/etc.

**Comment by Dreyfuzz** [comment]
Sorry, saw that this is a duplicate.
