### ISSUE TITLE
Could Not Find RubyGem haml

### ISSUE THREAD

**Issue by ghost** [handcrafted/handcrafted-haml-textmate-bundle#9]
Using a fresh install of Ruby 1.9.2 (via RVM), Textmate, and the Handcrafted Haml bundle, I get the following error when trying to convert from HTML to Haml:

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:827:in `report_activate_error': Could not find RubyGem haml (>= 0) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:261:in`activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:68:in `gem'
    from -e:1

I ran sudo gem install haml and it installed successfully. The output of ruby -v is 1.9.2p180. It seems like TM is still looking for my system (Mac OS X) version of Ruby, not the new one I installed. Any thoughts?

**Comment by zachinglis** [comment]
This is old, but I believe I know the answer.

Run "gem install haml" instead.

**Comment by Dreyfuzz** [comment]
Same issue.  I tried both with and without sudo. Any other steps?
